version: "3.9"
services:
    adminer:
        image: adminer
        restart: always
        ports:
            - 8089:8080
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"
